version: "3.0"
volumes:
  db_data:
services:
  mariadb:
    image: mariadb
    container_name: taller_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: shadowfax
    networks:
      taller-app:
        ipv4_address: 32.0.0.2
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: taller-phpmyadmin
    environment:
      PMA_HOST: mysql
    links:
      - "mariadb:mysql"
    ports:
      - 7300:80
    networks:
      taller-app:
        ipv4_address: 32.0.0.3
networks:
  taller-app:
    driver: bridge
    ipam:
      config:
        - subnet: 32.0.0.0/24
